#!/usr/bin/env python3
# ruff: noqa: E501
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

DATASET_ID = "acmeai-hybrid-reranker-replication-v1"
OUTPUT = Path("data/eval/acmeai_hybrid_reranker_replication_v1.json")
TOKEN = re.compile(r"[a-z0-9]+")
ACCEPTED_OVERLAP_CEILING = 0.5
FROZEN_PRIOR_MAXIMA = {
    "acmeai_hybrid_reranker_eval_v1.json": 0.4,
    "acmeai_sol_judge_e2e_eval_v1.json": 0.4444444444444444,
    "acmeai_evidence_judge_e2e_eval_v1.json": 0.47058823529411764,
    "acmeai_reranker_e2e_eval_v1.json": 0.391304347826087,
}


def terms(question: str) -> set[str]:
    return set(TOKEN.findall(question.casefold()))


def case(
    case_id: str,
    category: str,
    question: str,
    *,
    documents: list[str] | None = None,
    versions: dict[str, str] | None = None,
    answer: str | None = None,
    facts: list[str] | None = None,
    fact_ids: list[str] | None = None,
    forbidden: list[str] | None = None,
    access: str = "ALLOW_REQUIRED",
    answerable: bool = True,
    principal: dict[str, object] | None = None,
    security: list[str] | None = None,
) -> dict[str, object]:
    payload: dict[str, object] = {
        "case_id": case_id,
        "category": category,
        "question": question,
        "required_document_ids": documents or [],
        "required_chunk_ids": [],
        "required_version_ids": versions or {},
        "required_fact_ids": fact_ids or [],
        "expected_facts": facts or [],
        "expected_answer": answer,
        "forbidden_document_ids": forbidden or [],
        "expected_access_behavior": access,
        "expected_answerability": answerable,
        "should_abstain": not answerable,
        "expected_document_ids": documents or [],
        "expected_versions": versions or {},
        "security_checks": security or [],
    }
    if principal:
        payload["principal"] = principal
    return payload


EMPLOYEE = {
    "principal_id": "hrp-acl-employee",
    "tenant_id": "acmeai",
    "permission_groups": ["employees"],
}

CASES = [
    case(
        "hrp_two_01",
        "multidoc_two",
        "Adzeplate asks which group shepherds Atlas's interface layer and how long Operations budgets to restore the public customer surface.",
        documents=["project-atlas-api", "operations-continuity-plan"],
        versions={"project-atlas-api": "3.0", "operations-continuity-plan": "4.0"},
        answer="The Atlas API is maintained by the Platform Interfaces team. The recovery time objective for the customer API is four hours.",
        facts=["Platform Interfaces", "four hours"],
        fact_ids=["api_owner", "rto"],
    ),
    case(
        "hrp_two_02",
        "multidoc_two",
        "Bodkinmark wants the live weekly remote quota together with the overseas-travel authorization string Finance prints on forms.",
        documents=["remote-work-policy", "finance-expense-policy"],
        versions={"remote-work-policy": "2026", "finance-expense-policy": "5.1"},
        answer="Employees may work remotely two days per week. The international travel approval code is FIN-TRAVEL-52.",
        facts=["two days per week", "FIN-TRAVEL-52"],
        fact_ids=["remote_allowance", "travel_code"],
        security=["version"],
    ),
    case(
        "hrp_two_03",
        "multidoc_two",
        "Celtchip needs the eastern spare-site geography plus the literal erasure workflow legal operations accept.",
        documents=["recovery-runbook-east", "data-retention-standard"],
        versions={"recovery-runbook-east": "1.0", "data-retention-standard": "2.0"},
        answer="East-region failover targets the eu-central standby cluster. The approved deletion workflow identifier is LEGAL-DEL-08.",
        facts=["eu-central", "LEGAL-DEL-08"],
        fact_ids=["east_standby", "deletion_token"],
    ),
    case(
        "hrp_two_04",
        "multidoc_two",
        "Dibbletag records Atlas's opening customer geography beside the weekday pair used for ordinary production shipping.",
        documents=["project-atlas-launch", "engineering-deployment-handbook"],
        versions={"project-atlas-launch": "1.0", "engineering-deployment-handbook": "2026.1"},
        answer="The initial customer region for Project Atlas is eu-west. Routine production releases occur on Tuesdays and Thursdays.",
        facts=["eu-west", "Tuesdays and Thursdays"],
        fact_ids=["launch_region", "release_days"],
    ),
    case(
        "hrp_two_05",
        "multidoc_two",
        "Ellwand wants the clock for paging the duty officer on a top-severity event and the cadence of public customer notices after a queue item opens.",
        documents=["security-incident-policy", "customer-support-escalation"],
        versions={"security-incident-policy": "2026", "customer-support-escalation": "3.2"},
        answer="Suspected severity-one incidents must be reported to the security duty officer within 15 minutes. Customer-facing status updates are published every thirty minutes until mitigation.",
        facts=["15 minutes", "every thirty minutes"],
        fact_ids=["sev1_notice", "status_cadence"],
        security=["version"],
    ),
    case(
        "hrp_two_06",
        "multidoc_two",
        "Flaxtally pairs the western rehearsal weekday with the euro floor that forces a receipt.",
        documents=["recovery-runbook-west", "finance-expense-policy"],
        versions={"recovery-runbook-west": "1.0", "finance-expense-policy": "5.1"},
        answer="The west recovery drill runs on the second Wednesday of each quarter. Receipts are required for expenses above 25 euros.",
        facts=["second Wednesday", "25 euros"],
        fact_ids=["west_drill", "receipt_threshold"],
    ),
    case(
        "hrp_two_07",
        "multidoc_two",
        "Gimlethook wants the Product Operations owner of the Atlas introduction together with how long support tickets remain on file.",
        documents=["project-atlas-launch", "data-retention-standard"],
        versions={"project-atlas-launch": "1.0", "data-retention-standard": "2.0"},
        answer="The launch owner is the Product Operations team. Customer support tickets are retained for twenty-four months.",
        facts=["Product Operations", "twenty-four months"],
        fact_ids=["launch_owner", "ticket_retention"],
    ),
    case(
        "hrp_two_08",
        "multidoc_two",
        "Heddlecard needs the production-approval string engineers attach before sign-off and the eastern runbook code used for customer-API recovery.",
        documents=["engineering-deployment-handbook", "recovery-runbook-east"],
        versions={"engineering-deployment-handbook": "2026.1", "recovery-runbook-east": "1.0"},
        answer="The production deployment approval identifier is ENG-DEP-17. The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["ENG-DEP-17", "OPS-REC-E17"],
        fact_ids=["deploy_token", "east_code"],
    ),
    case(
        "hrp_two_09",
        "multidoc_two",
        "Inklechit asks who owns continuity planning and which function is paged once the priority-one outage queue item exists.",
        documents=["operations-continuity-plan", "customer-support-escalation"],
        versions={"operations-continuity-plan": "4.0", "customer-support-escalation": "3.2"},
        answer="Operations owns the business continuity plan. Support agents page Operations after opening the queue item.",
        facts=["Operations owns", "page Operations"],
        fact_ids=["bcp_owner", "page_ops"],
    ),
    case(
        "hrp_two_10",
        "multidoc_two",
        "Jennybar wants the current manager rhythm for checking remote calendars plus the Atlas live-contract generation number.",
        documents=["remote-work-policy", "project-atlas-api"],
        versions={"remote-work-policy": "2026", "project-atlas-api": "3.0"},
        answer="Managers review remote-work schedules every month. Project Atlas uses API version v3.",
        facts=["every month", "v3"],
        fact_ids=["remote_review", "api_version"],
        security=["version"],
    ),
    case(
        "hrp_three_01",
        "multidoc_three",
        "Kecklemark must join the four-hour customer-surface budget, Atlas contract generation v3, and the eu-west opening geography.",
        documents=["operations-continuity-plan", "project-atlas-api", "project-atlas-launch"],
        versions={
            "operations-continuity-plan": "4.0",
            "project-atlas-api": "3.0",
            "project-atlas-launch": "1.0",
        },
        answer="The recovery time objective for the customer API is four hours. Project Atlas uses API version v3. The initial customer region for Project Atlas is eu-west.",
        facts=["four hours", "v3", "eu-west"],
        fact_ids=["rto", "api_version", "launch_region"],
    ),
    case(
        "hrp_three_02",
        "multidoc_three",
        "Linstock wants Operations' continuity ownership, the ATLAS-API-301 endpoint string, and the Tuesday-Thursday shipping pair.",
        documents=["operations-continuity-plan", "project-atlas-api", "engineering-deployment-handbook"],
        versions={
            "operations-continuity-plan": "4.0",
            "project-atlas-api": "3.0",
            "engineering-deployment-handbook": "2026.1",
        },
        answer="Operations owns the business continuity plan. The production endpoint identifier is ATLAS-API-301. Routine production releases occur on Tuesdays and Thursdays.",
        facts=["Operations owns", "ATLAS-API-301", "Tuesdays and Thursdays"],
        fact_ids=["bcp_owner", "api_token", "release_days"],
    ),
    case(
        "hrp_three_03",
        "multidoc_three",
        "Marlinespike joins the customer-API restoration window, Platform Interfaces ownership, and the CS-1842 outage-queue string.",
        documents=["operations-continuity-plan", "project-atlas-api", "customer-support-escalation"],
        versions={
            "operations-continuity-plan": "4.0",
            "project-atlas-api": "3.0",
            "customer-support-escalation": "3.2",
        },
        answer="The recovery time objective for the customer API is four hours. The Atlas API is maintained by the Platform Interfaces team. The exact escalation queue identifier for a priority-one customer outage is CS-1842.",
        facts=["four hours", "Platform Interfaces", "CS-1842"],
        fact_ids=["rto", "api_owner", "queue_token"],
    ),
    case(
        "hrp_three_04",
        "multidoc_three",
        "Niddyknob records the four-hour restoration budget, Atlas v3, and the live two-day remote quota.",
        documents=["operations-continuity-plan", "project-atlas-api", "remote-work-policy"],
        versions={
            "operations-continuity-plan": "4.0",
            "project-atlas-api": "3.0",
            "remote-work-policy": "2026",
        },
        answer="The recovery time objective for the customer API is four hours. Project Atlas uses API version v3. Employees may work remotely two days per week.",
        facts=["four hours", "v3", "two days per week"],
        fact_ids=["rto", "api_version", "remote_allowance"],
        security=["version"],
    ),
    case(
        "hrp_three_05",
        "multidoc_three",
        "Oxgange wants Operations as continuity owner, Product Operations as Atlas introducer, and ENG-DEP-17 on the release ticket.",
        documents=["operations-continuity-plan", "project-atlas-launch", "engineering-deployment-handbook"],
        versions={
            "operations-continuity-plan": "4.0",
            "project-atlas-launch": "1.0",
            "engineering-deployment-handbook": "2026.1",
        },
        answer="Operations owns the business continuity plan. The launch owner is the Product Operations team. The production deployment approval identifier is ENG-DEP-17.",
        facts=["Operations owns", "Product Operations", "ENG-DEP-17"],
        fact_ids=["bcp_owner", "launch_owner", "deploy_token"],
    ),
    case(
        "hrp_three_06",
        "multidoc_three",
        "Pickhook joins the four-hour restoration budget, Atlas's April 12 2026 introduction, and twenty-four-month ticket storage.",
        documents=["operations-continuity-plan", "project-atlas-launch", "data-retention-standard"],
        versions={
            "operations-continuity-plan": "4.0",
            "project-atlas-launch": "1.0",
            "data-retention-standard": "2.0",
        },
        answer="The recovery time objective for the customer API is four hours. Project Atlas launched on April 12, 2026. Customer support tickets are retained for twenty-four months.",
        facts=["four hours", "April 12, 2026", "twenty-four months"],
        fact_ids=["rto", "launch_date", "ticket_retention"],
    ),
    case(
        "hrp_three_07",
        "multidoc_three",
        "Quernstone needs continuity ownership, Atlas's opening customer geography, and the spending-policy euro floor that forces a receipt.",
        documents=["operations-continuity-plan", "project-atlas-launch", "finance-expense-policy"],
        versions={
            "operations-continuity-plan": "4.0",
            "project-atlas-launch": "1.0",
            "finance-expense-policy": "5.1",
        },
        answer="Operations owns the business continuity plan. The initial customer region for Project Atlas is eu-west. Receipts are required for expenses above 25 euros.",
        facts=["Operations owns", "eu-west", "25 euros"],
        fact_ids=["bcp_owner", "launch_region", "receipt_threshold"],
    ),
    case(
        "hrp_three_08",
        "multidoc_three",
        "Riddleplate joins the four-hour restoration budget, Tuesday-Thursday shipping, and OPS-REC-E17.",
        documents=["operations-continuity-plan", "engineering-deployment-handbook", "recovery-runbook-east"],
        versions={
            "operations-continuity-plan": "4.0",
            "engineering-deployment-handbook": "2026.1",
            "recovery-runbook-east": "1.0",
        },
        answer="The recovery time objective for the customer API is four hours. Routine production releases occur on Tuesdays and Thursdays. The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["four hours", "Tuesdays and Thursdays", "OPS-REC-E17"],
        fact_ids=["rto", "release_days", "east_code"],
    ),
    case(
        "hrp_three_09",
        "multidoc_three",
        "Snathmark wants Operations as continuity owner, the incident-commander emergency-change path, and OPS-REC-W29.",
        documents=["operations-continuity-plan", "engineering-deployment-handbook", "recovery-runbook-west"],
        versions={
            "operations-continuity-plan": "4.0",
            "engineering-deployment-handbook": "2026.1",
            "recovery-runbook-west": "1.0",
        },
        answer="Operations owns the business continuity plan. Emergency changes follow the incident commander process. The west-region recovery sequence uses runbook code OPS-REC-W29.",
        facts=["Operations owns", "incident commander", "OPS-REC-W29"],
        fact_ids=["bcp_owner", "emergency_process", "west_code"],
    ),
    case(
        "hrp_three_10",
        "multidoc_three",
        "Tholepin joins the four-hour restoration budget, ENG-DEP-17, and the 15-minute duty-officer clock.",
        documents=["operations-continuity-plan", "engineering-deployment-handbook", "security-incident-policy"],
        versions={
            "operations-continuity-plan": "4.0",
            "engineering-deployment-handbook": "2026.1",
            "security-incident-policy": "2026",
        },
        answer="The recovery time objective for the customer API is four hours. The production deployment approval identifier is ENG-DEP-17. Suspected severity-one incidents must be reported to the security duty officer within 15 minutes.",
        facts=["four hours", "ENG-DEP-17", "15 minutes"],
        fact_ids=["rto", "deploy_token", "sev1_notice"],
        security=["version"],
    ),
    case(
        "hrp_three_11",
        "multidoc_three",
        "Ullagechit records continuity ownership, CS-1842, and seven-year defensive-log storage.",
        documents=["operations-continuity-plan", "customer-support-escalation", "data-retention-standard"],
        versions={
            "operations-continuity-plan": "4.0",
            "customer-support-escalation": "3.2",
            "data-retention-standard": "2.0",
        },
        answer="Operations owns the business continuity plan. The exact escalation queue identifier for a priority-one customer outage is CS-1842. Security audit logs are retained for seven years.",
        facts=["Operations owns", "CS-1842", "seven years"],
        fact_ids=["bcp_owner", "queue_token", "log_retention"],
    ),
    case(
        "hrp_three_12",
        "multidoc_three",
        "Vangtag wants the four-hour restoration budget, the thirty-minute public-notice cadence, and FIN-TRAVEL-52.",
        documents=["operations-continuity-plan", "customer-support-escalation", "finance-expense-policy"],
        versions={
            "operations-continuity-plan": "4.0",
            "customer-support-escalation": "3.2",
            "finance-expense-policy": "5.1",
        },
        answer="The recovery time objective for the customer API is four hours. Customer-facing status updates are published every thirty minutes until mitigation. The international travel approval code is FIN-TRAVEL-52.",
        facts=["four hours", "every thirty minutes", "FIN-TRAVEL-52"],
        fact_ids=["rto", "status_cadence", "travel_code"],
    ),
    case(
        "hrp_three_13",
        "multidoc_three",
        "Wimblecard joins continuity ownership, paging Operations after the queue opens, and eu-central eastern failover.",
        documents=["operations-continuity-plan", "customer-support-escalation", "recovery-runbook-east"],
        versions={
            "operations-continuity-plan": "4.0",
            "customer-support-escalation": "3.2",
            "recovery-runbook-east": "1.0",
        },
        answer="Operations owns the business continuity plan. Support agents page Operations after opening the queue item. East-region failover targets the eu-central standby cluster.",
        facts=["Operations owns", "page Operations", "eu-central"],
        fact_ids=["bcp_owner", "page_ops", "east_standby"],
    ),
    case(
        "hrp_three_14",
        "multidoc_three",
        "Xysterfolio wants the four-hour restoration budget, FIN-TRAVEL-52, and the live two-day remote quota.",
        documents=["operations-continuity-plan", "finance-expense-policy", "remote-work-policy"],
        versions={
            "operations-continuity-plan": "4.0",
            "finance-expense-policy": "5.1",
            "remote-work-policy": "2026",
        },
        answer="The recovery time objective for the customer API is four hours. The international travel approval code is FIN-TRAVEL-52. Employees may work remotely two days per week.",
        facts=["four hours", "FIN-TRAVEL-52", "two days per week"],
        fact_ids=["rto", "travel_code", "remote_allowance"],
        security=["version"],
    ),
    case(
        "hrp_three_15",
        "multidoc_three",
        "Yelveplate joins continuity ownership, the 25-euro receipt floor, and OPS-REC-E17.",
        documents=["operations-continuity-plan", "finance-expense-policy", "recovery-runbook-east"],
        versions={
            "operations-continuity-plan": "4.0",
            "finance-expense-policy": "5.1",
            "recovery-runbook-east": "1.0",
        },
        answer="Operations owns the business continuity plan. Receipts are required for expenses above 25 euros. The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["Operations owns", "25 euros", "OPS-REC-E17"],
        fact_ids=["bcp_owner", "receipt_threshold", "east_code"],
    ),
    case(
        "hrp_three_16",
        "multidoc_three",
        "Zaxmark records Product Operations as introducer, ATLAS-API-301, and Tuesday-Thursday shipping.",
        documents=["project-atlas-launch", "project-atlas-api", "engineering-deployment-handbook"],
        versions={
            "project-atlas-launch": "1.0",
            "project-atlas-api": "3.0",
            "engineering-deployment-handbook": "2026.1",
        },
        answer="The launch owner is the Product Operations team. The production endpoint identifier is ATLAS-API-301. Routine production releases occur on Tuesdays and Thursdays.",
        facts=["Product Operations", "ATLAS-API-301", "Tuesdays and Thursdays"],
        fact_ids=["launch_owner", "api_token", "release_days"],
    ),
    case(
        "hrp_three_17",
        "multidoc_three",
        "Anvilchip wants Atlas's April 12 2026 introduction, Platform Interfaces ownership, and CS-1842.",
        documents=["project-atlas-launch", "project-atlas-api", "customer-support-escalation"],
        versions={
            "project-atlas-launch": "1.0",
            "project-atlas-api": "3.0",
            "customer-support-escalation": "3.2",
        },
        answer="Project Atlas launched on April 12, 2026. The Atlas API is maintained by the Platform Interfaces team. The exact escalation queue identifier for a priority-one customer outage is CS-1842.",
        facts=["April 12, 2026", "Platform Interfaces", "CS-1842"],
        fact_ids=["launch_date", "api_owner", "queue_token"],
    ),
    case(
        "hrp_three_18",
        "multidoc_three",
        "Burrstone joins eu-west opening geography, Atlas v3, and the live monthly remote-calendar check.",
        documents=["project-atlas-launch", "project-atlas-api", "remote-work-policy"],
        versions={
            "project-atlas-launch": "1.0",
            "project-atlas-api": "3.0",
            "remote-work-policy": "2026",
        },
        answer="The initial customer region for Project Atlas is eu-west. Project Atlas uses API version v3. Managers review remote-work schedules every month.",
        facts=["eu-west", "v3", "every month"],
        fact_ids=["launch_region", "api_version", "remote_review"],
        security=["version"],
    ),
    case(
        "hrp_three_19",
        "multidoc_three",
        "Clevispin wants Product Operations as introducer, ATLAS-API-301, and OPS-REC-E17.",
        documents=["project-atlas-launch", "project-atlas-api", "recovery-runbook-east"],
        versions={
            "project-atlas-launch": "1.0",
            "project-atlas-api": "3.0",
            "recovery-runbook-east": "1.0",
        },
        answer="The launch owner is the Product Operations team. The production endpoint identifier is ATLAS-API-301. The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["Product Operations", "ATLAS-API-301", "OPS-REC-E17"],
        fact_ids=["launch_owner", "api_token", "east_code"],
    ),
    case(
        "hrp_three_20",
        "multidoc_three",
        "Driftpin joins April 12 2026, Platform Interfaces, and the us-east western spare site.",
        documents=["project-atlas-launch", "project-atlas-api", "recovery-runbook-west"],
        versions={
            "project-atlas-launch": "1.0",
            "project-atlas-api": "3.0",
            "recovery-runbook-west": "1.0",
        },
        answer="Project Atlas launched on April 12, 2026. The Atlas API is maintained by the Platform Interfaces team. West-region failover targets the us-east standby cluster.",
        facts=["April 12, 2026", "Platform Interfaces", "us-east"],
        fact_ids=["launch_date", "api_owner", "west_standby"],
    ),
    case(
        "hrp_three_21",
        "multidoc_three",
        "Eyeplate wants eu-west opening geography, Atlas v3, and the 15-minute duty-officer clock.",
        documents=["project-atlas-launch", "project-atlas-api", "security-incident-policy"],
        versions={
            "project-atlas-launch": "1.0",
            "project-atlas-api": "3.0",
            "security-incident-policy": "2026",
        },
        answer="The initial customer region for Project Atlas is eu-west. Project Atlas uses API version v3. Suspected severity-one incidents must be reported to the security duty officer within 15 minutes.",
        facts=["eu-west", "v3", "15 minutes"],
        fact_ids=["launch_region", "api_version", "sev1_notice"],
        security=["version"],
    ),
    case(
        "hrp_three_22",
        "multidoc_three",
        "Fidhook joins ATLAS-API-301, ENG-DEP-17, and CS-1842.",
        documents=["project-atlas-api", "engineering-deployment-handbook", "customer-support-escalation"],
        versions={
            "project-atlas-api": "3.0",
            "engineering-deployment-handbook": "2026.1",
            "customer-support-escalation": "3.2",
        },
        answer="The production endpoint identifier is ATLAS-API-301. The production deployment approval identifier is ENG-DEP-17. The exact escalation queue identifier for a priority-one customer outage is CS-1842.",
        facts=["ATLAS-API-301", "ENG-DEP-17", "CS-1842"],
        fact_ids=["api_token", "deploy_token", "queue_token"],
    ),
    case(
        "hrp_three_23",
        "multidoc_three",
        "Grommettag wants Platform Interfaces ownership, Tuesday-Thursday shipping, and OPS-REC-E17.",
        documents=["project-atlas-api", "engineering-deployment-handbook", "recovery-runbook-east"],
        versions={
            "project-atlas-api": "3.0",
            "engineering-deployment-handbook": "2026.1",
            "recovery-runbook-east": "1.0",
        },
        answer="The Atlas API is maintained by the Platform Interfaces team. Routine production releases occur on Tuesdays and Thursdays. The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["Platform Interfaces", "Tuesdays and Thursdays", "OPS-REC-E17"],
        fact_ids=["api_owner", "release_days", "east_code"],
    ),
    case(
        "hrp_three_24",
        "multidoc_three",
        "Halyardpin joins Atlas v3, ENG-DEP-17, and OPS-REC-W29.",
        documents=["project-atlas-api", "engineering-deployment-handbook", "recovery-runbook-west"],
        versions={
            "project-atlas-api": "3.0",
            "engineering-deployment-handbook": "2026.1",
            "recovery-runbook-west": "1.0",
        },
        answer="Project Atlas uses API version v3. The production deployment approval identifier is ENG-DEP-17. The west-region recovery sequence uses runbook code OPS-REC-W29.",
        facts=["v3", "ENG-DEP-17", "OPS-REC-W29"],
        fact_ids=["api_version", "deploy_token", "west_code"],
    ),
    case(
        "hrp_three_25",
        "multidoc_three",
        "Ironbeck wants ATLAS-API-301, the emergency-change process, and who the commander coordinates during a top-class event.",
        documents=["project-atlas-api", "engineering-deployment-handbook", "security-incident-policy"],
        versions={
            "project-atlas-api": "3.0",
            "engineering-deployment-handbook": "2026.1",
            "security-incident-policy": "2026",
        },
        answer="The production endpoint identifier is ATLAS-API-301. Emergency changes follow the incident commander process. The incident commander coordinates Engineering and Customer Support during an active severity-one incident.",
        facts=["ATLAS-API-301", "incident commander", "Engineering and Customer Support"],
        fact_ids=["api_token", "emergency_process", "coord_groups"],
        security=["version"],
    ),
    case(
        "hrp_three_26",
        "multidoc_three",
        "Jawhitch joins Platform Interfaces, the thirty-minute public-notice cadence, and the live two-day remote quota.",
        documents=["project-atlas-api", "customer-support-escalation", "remote-work-policy"],
        versions={
            "project-atlas-api": "3.0",
            "customer-support-escalation": "3.2",
            "remote-work-policy": "2026",
        },
        answer="The Atlas API is maintained by the Platform Interfaces team. Customer-facing status updates are published every thirty minutes until mitigation. Employees may work remotely two days per week.",
        facts=["Platform Interfaces", "every thirty minutes", "two days per week"],
        fact_ids=["api_owner", "status_cadence", "remote_allowance"],
        security=["version"],
    ),
    case(
        "hrp_three_27",
        "multidoc_three",
        "Kevelmark wants Atlas v3, CS-1842, and the first-Wednesday eastern rehearsal.",
        documents=["project-atlas-api", "customer-support-escalation", "recovery-runbook-east"],
        versions={
            "project-atlas-api": "3.0",
            "customer-support-escalation": "3.2",
            "recovery-runbook-east": "1.0",
        },
        answer="Project Atlas uses API version v3. The exact escalation queue identifier for a priority-one customer outage is CS-1842. The east recovery drill runs on the first Wednesday of each quarter.",
        facts=["v3", "CS-1842", "first Wednesday"],
        fact_ids=["api_version", "queue_token", "east_drill"],
    ),
    case(
        "hrp_three_28",
        "multidoc_three",
        "Lanyardtag joins ATLAS-API-301, the in-force weekly remote allowance, and the eastern spare-site geography.",
        documents=["project-atlas-api", "remote-work-policy", "recovery-runbook-east"],
        versions={
            "project-atlas-api": "3.0",
            "remote-work-policy": "2026",
            "recovery-runbook-east": "1.0",
        },
        answer="The production endpoint identifier is ATLAS-API-301. Employees may work remotely two days per week. East-region failover targets the eu-central standby cluster.",
        facts=["ATLAS-API-301", "two days per week", "eu-central"],
        fact_ids=["api_token", "remote_allowance", "east_standby"],
        security=["version"],
    ),
    case(
        "hrp_three_29",
        "multidoc_three",
        "Mastband wants Platform Interfaces, monthly remote-calendar checks, and the us-east western spare site.",
        documents=["project-atlas-api", "remote-work-policy", "recovery-runbook-west"],
        versions={
            "project-atlas-api": "3.0",
            "remote-work-policy": "2026",
            "recovery-runbook-west": "1.0",
        },
        answer="The Atlas API is maintained by the Platform Interfaces team. Managers review remote-work schedules every month. West-region failover targets the us-east standby cluster.",
        facts=["Platform Interfaces", "every month", "us-east"],
        fact_ids=["api_owner", "remote_review", "west_standby"],
        security=["version"],
    ),
    case(
        "hrp_three_30",
        "multidoc_three",
        "Noseclamp joins April 12 2026, ENG-DEP-17, and CS-1842.",
        documents=["project-atlas-launch", "engineering-deployment-handbook", "customer-support-escalation"],
        versions={
            "project-atlas-launch": "1.0",
            "engineering-deployment-handbook": "2026.1",
            "customer-support-escalation": "3.2",
        },
        answer="Project Atlas launched on April 12, 2026. The production deployment approval identifier is ENG-DEP-17. The exact escalation queue identifier for a priority-one customer outage is CS-1842.",
        facts=["April 12, 2026", "ENG-DEP-17", "CS-1842"],
        fact_ids=["launch_date", "deploy_token", "queue_token"],
    ),
    case(
        "hrp_three_31",
        "multidoc_three",
        "Oakumroll wants eu-west opening geography, Tuesday-Thursday shipping, and the live two-day remote quota.",
        documents=["project-atlas-launch", "engineering-deployment-handbook", "remote-work-policy"],
        versions={
            "project-atlas-launch": "1.0",
            "engineering-deployment-handbook": "2026.1",
            "remote-work-policy": "2026",
        },
        answer="The initial customer region for Project Atlas is eu-west. Routine production releases occur on Tuesdays and Thursdays. Employees may work remotely two days per week.",
        facts=["eu-west", "Tuesdays and Thursdays", "two days per week"],
        fact_ids=["launch_region", "release_days", "remote_allowance"],
        security=["version"],
    ),
    case(
        "hrp_three_32",
        "multidoc_three",
        "Parrelbead joins Product Operations as introducer, ENG-DEP-17, and OPS-REC-E17.",
        documents=["project-atlas-launch", "engineering-deployment-handbook", "recovery-runbook-east"],
        versions={
            "project-atlas-launch": "1.0",
            "engineering-deployment-handbook": "2026.1",
            "recovery-runbook-east": "1.0",
        },
        answer="The launch owner is the Product Operations team. The production deployment approval identifier is ENG-DEP-17. The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["Product Operations", "ENG-DEP-17", "OPS-REC-E17"],
        fact_ids=["launch_owner", "deploy_token", "east_code"],
    ),
    case(
        "hrp_three_33",
        "multidoc_three",
        "Quoinblock wants April 12 2026, the thirty-minute public-notice cadence, and the live monthly remote-calendar check.",
        documents=["project-atlas-launch", "customer-support-escalation", "remote-work-policy"],
        versions={
            "project-atlas-launch": "1.0",
            "customer-support-escalation": "3.2",
            "remote-work-policy": "2026",
        },
        answer="Project Atlas launched on April 12, 2026. Customer-facing status updates are published every thirty minutes until mitigation. Managers review remote-work schedules every month.",
        facts=["April 12, 2026", "every thirty minutes", "every month"],
        fact_ids=["launch_date", "status_cadence", "remote_review"],
        security=["version"],
    ),
    case(
        "hrp_three_34",
        "multidoc_three",
        "Rowlockpin joins eu-west opening geography, CS-1842, and the first-Wednesday eastern rehearsal.",
        documents=["project-atlas-launch", "customer-support-escalation", "recovery-runbook-east"],
        versions={
            "project-atlas-launch": "1.0",
            "customer-support-escalation": "3.2",
            "recovery-runbook-east": "1.0",
        },
        answer="The initial customer region for Project Atlas is eu-west. The exact escalation queue identifier for a priority-one customer outage is CS-1842. The east recovery drill runs on the first Wednesday of each quarter.",
        facts=["eu-west", "CS-1842", "first Wednesday"],
        fact_ids=["launch_region", "queue_token", "east_drill"],
    ),
    case(
        "hrp_three_35",
        "multidoc_three",
        "Shacklekey wants Product Operations as introducer, the in-force weekly remote allowance, and the eastern spare-site geography.",
        documents=["project-atlas-launch", "remote-work-policy", "recovery-runbook-east"],
        versions={
            "project-atlas-launch": "1.0",
            "remote-work-policy": "2026",
            "recovery-runbook-east": "1.0",
        },
        answer="The launch owner is the Product Operations team. Employees may work remotely two days per week. East-region failover targets the eu-central standby cluster.",
        facts=["Product Operations", "two days per week", "eu-central"],
        fact_ids=["launch_owner", "remote_allowance", "east_standby"],
        security=["version"],
    ),
    case(
        "hrp_three_36",
        "multidoc_three",
        "Tillerhead joins April 12 2026, monthly remote-calendar checks, and the 15-minute duty-officer clock.",
        documents=["project-atlas-launch", "remote-work-policy", "security-incident-policy"],
        versions={
            "project-atlas-launch": "1.0",
            "remote-work-policy": "2026",
            "security-incident-policy": "2026",
        },
        answer="Project Atlas launched on April 12, 2026. Managers review remote-work schedules every month. Suspected severity-one incidents must be reported to the security duty officer within 15 minutes.",
        facts=["April 12, 2026", "every month", "15 minutes"],
        fact_ids=["launch_date", "remote_review", "sev1_notice"],
        security=["version"],
    ),
    case(
        "hrp_three_37",
        "multidoc_three",
        "Uptakeclew wants ENG-DEP-17, CS-1842, and the live two-day remote quota.",
        documents=["engineering-deployment-handbook", "customer-support-escalation", "remote-work-policy"],
        versions={
            "engineering-deployment-handbook": "2026.1",
            "customer-support-escalation": "3.2",
            "remote-work-policy": "2026",
        },
        answer="The production deployment approval identifier is ENG-DEP-17. The exact escalation queue identifier for a priority-one customer outage is CS-1842. Employees may work remotely two days per week.",
        facts=["ENG-DEP-17", "CS-1842", "two days per week"],
        fact_ids=["deploy_token", "queue_token", "remote_allowance"],
        security=["version"],
    ),
    case(
        "hrp_three_38",
        "multidoc_three",
        "Vangblock joins Tuesday-Thursday shipping, the thirty-minute public-notice cadence, and OPS-REC-W29.",
        documents=["engineering-deployment-handbook", "customer-support-escalation", "recovery-runbook-west"],
        versions={
            "engineering-deployment-handbook": "2026.1",
            "customer-support-escalation": "3.2",
            "recovery-runbook-west": "1.0",
        },
        answer="Routine production releases occur on Tuesdays and Thursdays. Customer-facing status updates are published every thirty minutes until mitigation. The west-region recovery sequence uses runbook code OPS-REC-W29.",
        facts=["Tuesdays and Thursdays", "every thirty minutes", "OPS-REC-W29"],
        fact_ids=["release_days", "status_cadence", "west_code"],
    ),
    case(
        "hrp_three_39",
        "multidoc_three",
        "Whelpdrum wants ENG-DEP-17, monthly remote-calendar checks, and OPS-REC-E17.",
        documents=["engineering-deployment-handbook", "remote-work-policy", "recovery-runbook-east"],
        versions={
            "engineering-deployment-handbook": "2026.1",
            "remote-work-policy": "2026",
            "recovery-runbook-east": "1.0",
        },
        answer="The production deployment approval identifier is ENG-DEP-17. Managers review remote-work schedules every month. The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["ENG-DEP-17", "every month", "OPS-REC-E17"],
        fact_ids=["deploy_token", "remote_review", "east_code"],
        security=["version"],
    ),
    case(
        "hrp_three_40",
        "multidoc_three",
        "Yardgant joins LEGAL-DEL-08, Finance Operations as exception owner, and the second-Wednesday western rehearsal.",
        documents=["data-retention-standard", "finance-expense-policy", "recovery-runbook-west"],
        versions={
            "data-retention-standard": "2.0",
            "finance-expense-policy": "5.1",
            "recovery-runbook-west": "1.0",
        },
        answer="The approved deletion workflow identifier is LEGAL-DEL-08. Finance Operations owns exception review. The west recovery drill runs on the second Wednesday of each quarter.",
        facts=["LEGAL-DEL-08", "Finance Operations", "second Wednesday"],
        fact_ids=["deletion_token", "exception_owner", "west_drill"],
    ),
    case(
        "hrp_near_01",
        "near_duplicate",
        "Adzefork should prefer the east recovery pamphlet whose sequence marker is OPS-REC-E17 over its western counterpart.",
        documents=["recovery-runbook-east"],
        versions={"recovery-runbook-east": "1.0"},
        forbidden=["recovery-runbook-west"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="The east-region customer API recovery sequence uses runbook code OPS-REC-E17.",
        facts=["OPS-REC-E17"],
        fact_ids=["east_code"],
    ),
    case(
        "hrp_near_02",
        "near_duplicate",
        "Bodkinfork should prefer the west recovery pamphlet whose standby geography is us-east over its eastern counterpart.",
        documents=["recovery-runbook-west"],
        versions={"recovery-runbook-west": "1.0"},
        forbidden=["recovery-runbook-east"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="West-region failover targets the us-east standby cluster.",
        facts=["us-east"],
        fact_ids=["west_standby"],
    ),
    case(
        "hrp_near_03",
        "near_duplicate",
        "Celtfork should prefer the Atlas introduction brief owned by Product Operations rather than the sibling endpoint guide.",
        documents=["project-atlas-launch"],
        versions={"project-atlas-launch": "1.0"},
        forbidden=["project-atlas-api"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="The launch owner is the Product Operations team.",
        facts=["Product Operations"],
        fact_ids=["launch_owner"],
    ),
    case(
        "hrp_near_04",
        "near_duplicate",
        "Dibblefork should prefer the Atlas endpoint guide owned by Platform Interfaces rather than the sibling introduction brief.",
        documents=["project-atlas-api"],
        versions={"project-atlas-api": "3.0"},
        forbidden=["project-atlas-launch"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="The Atlas API is maintained by the Platform Interfaces team.",
        facts=["Platform Interfaces"],
        fact_ids=["api_owner"],
    ),
    case(
        "hrp_near_05",
        "near_duplicate",
        "Ellwandfork should prefer the records standard whose audit-log horizon is seven years over the finance claims pamphlet.",
        documents=["data-retention-standard"],
        versions={"data-retention-standard": "2.0"},
        forbidden=["finance-expense-policy"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="Security audit logs are retained for seven years.",
        facts=["seven years"],
        fact_ids=["log_retention"],
    ),
    case(
        "hrp_near_06",
        "near_duplicate",
        "Flaxfork should prefer the spending standard whose filing window is ten business days rather than the records standard.",
        documents=["finance-expense-policy"],
        versions={"finance-expense-policy": "5.1"},
        forbidden=["data-retention-standard"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="Expense reports are due within ten business days.",
        facts=["ten business days"],
        fact_ids=["expense_deadline"],
    ),
    case(
        "hrp_near_07",
        "near_duplicate",
        "Gimletfork should prefer the east recovery pamphlet whose drill falls on the opening Wednesday rather than the western counterpart.",
        documents=["recovery-runbook-east"],
        versions={"recovery-runbook-east": "1.0"},
        forbidden=["recovery-runbook-west"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="The east recovery drill runs on the first Wednesday of each quarter.",
        facts=["first Wednesday"],
        fact_ids=["east_drill"],
    ),
    case(
        "hrp_near_08",
        "near_duplicate",
        "Heddlefork should prefer the west recovery pamphlet whose drill falls on the second Wednesday rather than the eastern counterpart.",
        documents=["recovery-runbook-west"],
        versions={"recovery-runbook-west": "1.0"},
        forbidden=["recovery-runbook-east"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="The west recovery drill runs on the second Wednesday of each quarter.",
        facts=["second Wednesday"],
        fact_ids=["west_drill"],
    ),
    case(
        "hrp_id_01",
        "exact_identifier",
        "Jennyfolio must transcribe the literal production-approval identifier engineers attach before sign-off.",
        documents=["engineering-deployment-handbook"],
        versions={"engineering-deployment-handbook": "2026.1"},
        answer="The production deployment approval identifier is ENG-DEP-17.",
        facts=["ENG-DEP-17"],
        fact_ids=["deploy_token"],
    ),
    case(
        "hrp_id_02",
        "exact_identifier",
        "Kecklefolio must transcribe the literal priority-one outage queue identifier support opens first.",
        documents=["customer-support-escalation"],
        versions={"customer-support-escalation": "3.2"},
        answer="The exact escalation queue identifier for a priority-one customer outage is CS-1842.",
        facts=["CS-1842"],
        fact_ids=["queue_token"],
    ),
    case(
        "hrp_id_03",
        "exact_identifier",
        "Linstockfolio must transcribe the literal Atlas production endpoint identifier.",
        documents=["project-atlas-api"],
        versions={"project-atlas-api": "3.0"},
        answer="The production endpoint identifier is ATLAS-API-301.",
        facts=["ATLAS-API-301"],
        fact_ids=["api_token"],
    ),
    case(
        "hrp_id_04",
        "exact_identifier",
        "Marlinefolio must transcribe FIN-TRAVEL-52 from the spending standard.",
        documents=["finance-expense-policy"],
        versions={"finance-expense-policy": "5.1"},
        answer="The international travel approval code is FIN-TRAVEL-52.",
        facts=["FIN-TRAVEL-52"],
        fact_ids=["travel_code"],
    ),
    case(
        "hrp_id_05",
        "exact_identifier",
        "Niddyfolio must transcribe LEGAL-DEL-08 from the records standard.",
        documents=["data-retention-standard"],
        versions={"data-retention-standard": "2.0"},
        answer="The approved deletion workflow identifier is LEGAL-DEL-08.",
        facts=["LEGAL-DEL-08"],
        fact_ids=["deletion_token"],
    ),
    case(
        "hrp_id_06",
        "exact_identifier",
        "Oxgangfolio must transcribe the training-example catalog identifier printed next to the hostile quotation.",
        documents=["security-training-example"],
        versions={"security-training-example": "1"},
        answer="The training reference identifier is SEC-TRAIN-44.",
        facts=["SEC-TRAIN-44"],
        fact_ids=["training_id"],
        security=["prompt_injection"],
    ),
    case(
        "hrp_ver_01",
        "version_region",
        "Pickhookfolio: ignore the retired three-day remote rule; what weekly remote allowance is in force for 2026?",
        documents=["remote-work-policy"],
        versions={"remote-work-policy": "2026"},
        access="ACTIVE_VERSION_ONLY",
        answer="Under the current 2026 policy, employees may work remotely two days per week.",
        facts=["two days per week"],
        fact_ids=["remote_allowance"],
        security=["version"],
    ),
    case(
        "hrp_ver_02",
        "version_region",
        "Quernfolio: ignore the retired sixty-minute notice; how soon must a suspected top-class event reach the duty officer now?",
        documents=["security-incident-policy"],
        versions={"security-incident-policy": "2026"},
        access="ACTIVE_VERSION_ONLY",
        answer="Under the current 2026 policy, suspected severity-one incidents must be reported to the security duty officer within 15 minutes of discovery.",
        facts=["15 minutes"],
        fact_ids=["sev1_notice"],
        security=["version"],
    ),
    case(
        "hrp_ver_03",
        "version_region",
        "Riddlefolio: under the in-force people-ops rule, how frequently do managers inspect remote calendars?",
        documents=["remote-work-policy"],
        versions={"remote-work-policy": "2026"},
        access="ACTIVE_VERSION_ONLY",
        answer="Managers review remote-work schedules every month.",
        facts=["every month"],
        fact_ids=["remote_review"],
        security=["version"],
    ),
    case(
        "hrp_ver_04",
        "version_region",
        "Snathfolio: from the east-only recovery pamphlet, which standby geography takes customer-API traffic?",
        documents=["recovery-runbook-east"],
        versions={"recovery-runbook-east": "1.0"},
        forbidden=["recovery-runbook-west"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="East-region failover targets the eu-central standby cluster.",
        facts=["eu-central"],
        fact_ids=["east_standby"],
    ),
    case(
        "hrp_ver_05",
        "version_region",
        "Tholefolio: from the west-only recovery pamphlet, which standby geography takes traffic?",
        documents=["recovery-runbook-west"],
        versions={"recovery-runbook-west": "1.0"},
        forbidden=["recovery-runbook-east"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="West-region failover targets the us-east standby cluster.",
        facts=["us-east"],
        fact_ids=["west_standby"],
    ),
    case(
        "hrp_ver_06",
        "version_region",
        "Ullagefolio: does the east-only recovery pamphlet schedule its drill on the first Wednesday?",
        documents=["recovery-runbook-east"],
        versions={"recovery-runbook-east": "1.0"},
        forbidden=["recovery-runbook-west"],
        access="PREFER_REQUIRED_EXCLUDE_SIMILAR",
        answer="The east recovery drill runs on the first Wednesday of each quarter.",
        facts=["first Wednesday"],
        fact_ids=["east_drill"],
    ),
    case(
        "hrp_sem_01",
        "semantic_paraphrase",
        "Vangfolio: after a worst-class outage, what publication interval applies to customer bulletins, and who is radioed once the ticket exists?",
        documents=["customer-support-escalation"],
        versions={"customer-support-escalation": "3.2"},
        answer="Customer-facing status updates are published every thirty minutes until mitigation. Support agents page Operations after opening the queue item.",
        facts=["every thirty minutes", "page Operations"],
        fact_ids=["status_cadence", "page_ops"],
    ),
    case(
        "hrp_sem_02",
        "semantic_paraphrase",
        "Wimblefolio: what restoration window applies to the public customer surface, and which department authored the continuity pamphlet?",
        documents=["operations-continuity-plan"],
        versions={"operations-continuity-plan": "4.0"},
        answer="The recovery time objective for the customer API is four hours. Operations owns the business continuity plan.",
        facts=["four hours", "Operations"],
        fact_ids=["rto", "bcp_owner"],
    ),
    case(
        "hrp_sem_03",
        "semantic_paraphrase",
        "Xysterask: above what euro spend must a receipt be attached, and which finance group adjudicates exceptions?",
        documents=["finance-expense-policy"],
        versions={"finance-expense-policy": "5.1"},
        answer="Receipts are required for expenses above 25 euros. Finance Operations owns exception review.",
        facts=["25 euros", "Finance Operations"],
        fact_ids=["receipt_threshold", "exception_owner"],
    ),
    case(
        "hrp_sem_04",
        "semantic_paraphrase",
        "Yelvefolio: what retention horizon applies to security audit logs, and what retention horizon applies to support tickets?",
        documents=["data-retention-standard"],
        versions={"data-retention-standard": "2.0"},
        answer="Security audit logs are retained for seven years. Customer support tickets are retained for twenty-four months.",
        facts=["seven years", "twenty-four months"],
        fact_ids=["log_retention", "ticket_retention"],
    ),
    case(
        "hrp_acl_01",
        "acl_sensitive",
        "Zaxacl: a staffer without hr-leadership clearance asks for the internal executive compensation review code.",
        forbidden=["hr-compensation-bands"],
        access="EXCLUDE_FORBIDDEN",
        answerable=False,
        principal={**EMPLOYEE, "principal_id": "hrp-acl-01"},
        security=["acl"],
    ),
    case(
        "hrp_acl_02",
        "acl_sensitive",
        "Adzeacl: a staffer without hr-leadership clearance asks for the executive benefits exception identifier reviewed on Fridays.",
        forbidden=["hr-benefits-private"],
        access="EXCLUDE_FORBIDDEN",
        answerable=False,
        principal={**EMPLOYEE, "principal_id": "hrp-acl-02"},
        security=["acl"],
    ),
    case(
        "hrp_acl_03",
        "acl_sensitive",
        "Bodkinacl: a staffer without hr-leadership clearance asks for both hidden identifiers HR-COMP-900 and HR-BEN-771.",
        forbidden=["hr-compensation-bands", "hr-benefits-private"],
        access="EXCLUDE_FORBIDDEN",
        answerable=False,
        principal={**EMPLOYEE, "principal_id": "hrp-acl-03"},
        security=["acl"],
    ),
    case(
        "hrp_no_01",
        "partial_no_answer",
        "Celtnone: name the Product Operations owner of Atlas's introduction plus the fictional moss-farm ski-lift underwriter.",
        documents=["project-atlas-launch"],
        versions={"project-atlas-launch": "1.0"},
        access="ALLOW_PARTIAL",
        answerable=False,
        fact_ids=["launch_owner"],
    ),
    case(
        "hrp_no_02",
        "partial_no_answer",
        "Dibblenone: where is the fictional peat-bog zipline catalogued and what SKU tags it?",
        access="NO_SUPPORTED_EVIDENCE",
        answerable=False,
    ),
    case(
        "hrp_no_03",
        "partial_no_answer",
        "Ellwandnone: state the customer-API restoration window plus the fictional comet-warehouse skate-lease identifier.",
        documents=["operations-continuity-plan"],
        versions={"operations-continuity-plan": "4.0"},
        access="ALLOW_PARTIAL",
        answerable=False,
        fact_ids=["rto"],
    ),
]


def pairwise_maximum(left_questions: list[str], right_questions: list[str]) -> float:
    maximum = 0.0
    left_terms = [terms(question) for question in left_questions]
    right_terms = [terms(question) for question in right_questions]
    for left in left_terms:
        for right in right_terms:
            maximum = max(maximum, len(left & right) / len(left | right))
    return maximum


def maximum_prior_overlap() -> tuple[float, dict[str, float]]:
    new_questions = [str(item["question"]) for item in CASES]
    overall = 0.0
    per_file: dict[str, float] = {}
    for path in sorted(Path("data/eval").glob("*.json")):
        if path == OUTPUT:
            continue
        previous = [item["question"] for item in json.loads(path.read_text()).get("cases", [])]
        score = pairwise_maximum(new_questions, previous)
        per_file[path.name] = score
        overall = max(overall, score)
    return overall, per_file


def main() -> None:
    if len(CASES) != 80:
        raise SystemExit(f"expected 80 cases, found {len(CASES)}")
    expected = {
        "multidoc_two": 10,
        "multidoc_three": 40,
        "near_duplicate": 8,
        "exact_identifier": 6,
        "version_region": 6,
        "semantic_paraphrase": 4,
        "acl_sensitive": 3,
        "partial_no_answer": 3,
    }
    counts = {key: sum(item["category"] == key for item in CASES) for key in expected}
    if counts != expected:
        raise SystemExit(f"distribution mismatch: {counts}")
    if len({item["case_id"] for item in CASES}) != 80:
        raise SystemExit("duplicate case ids")
    if len({item["question"] for item in CASES}) != 80:
        raise SystemExit("duplicate questions")
    payload = {
        "dataset_id": DATASET_ID,
        "dataset_version": DATASET_ID,
        "corpus_version": "acmeai-v1",
        "generation_method": "manual-corpus-grounded-v1",
        "cases": CASES,
    }
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n")
    digest = hashlib.sha256(OUTPUT.read_bytes()).hexdigest()
    overlap, per_file = maximum_prior_overlap()
    print(
        json.dumps(
            {
                "dataset_hash": digest,
                "maximum_prior_overlap": overlap,
                "per_file_overlap": per_file,
                "case_count": len(CASES),
            },
            indent=2,
        )
    )
    if overlap >= ACCEPTED_OVERLAP_CEILING:
        raise SystemExit("overlap guard failed")
    for name, ceiling in FROZEN_PRIOR_MAXIMA.items():
        if per_file.get(name, 0.0) > ceiling + 1e-12:
            raise SystemExit(f"new dataset would raise frozen overlap for {name}")


if __name__ == "__main__":
    main()
